# Example Config
cd: /home/user/payment-checker # Working directory
google_sheets: # Update check history in Google Sheets
  sa_secrets_file: /home/user/payment-checker/secret.json # Google service account secrets file
  spreadsheet_id: 11111111111111111111111111111111111111111111 # Google Sheets ID
  sheet_name: Payments Status # Google Sheets Sheet Name
telegram:
  chat_id: -1001234567890 # Telegram chat ID
  token: 123456789:ABCdefGhIJKlmnoPQRstuVWXyz # Telegram bot token
accounts:
  - type: Hetzner
    login: user@example.com
    password: password123
    2fa: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA # 2FA code, Hetzner supported
    proxy: # Proxy is optional and supported for all providers
      server: socks5://1.2.3.4:111
  - type: RedSwitches
    login: user@example.com
    password: password123
